
name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: [8.2, 8.3, 8.4]
        #dependencies: [lowest, highest]
        stability: [prefer-lowest, prefer-stable]
        #stability: [prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, fileinfo, zip, pdo, sqlite, pdo_sqlite, bcmath

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest

  report-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: intl, fileinfo, zip, pdo, sqlite, pdo_sqlite, bcmath
          coverage: pcov

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Setup testbench
        run: php vendor/bin/testbench package:purge-skeleton --ansi

      - name: Execute tests with coverage
        run: vendor/bin/pest --coverage-clover=reports/coverage/test-coverage-clover.xml

      - name: Execute type coverage tests
        run: vendor/bin/pest --type-coverage --type-coverage-json=reports/coverage/pest-types-coverage.json

      - name: Upload Coverage Reports
        env:
          OTTERWISE_TOKEN: ${{ secrets.OTTERWISE_TOKEN }}
        run: bash <(curl -s https://raw.githubusercontent.com/getOtterWise/bash-uploader/main/uploader.sh) --file reports/coverage/test-coverage-clover.xml --type-coverage-file reports/coverage/pest-types-coverage.json
